56

diff --git a/apptainer.ompi41x/Singularity b/apptainer.ompi41x/Singularity
--- a/apptainer.ompi41x/Singularity
+++ b/apptainer.ompi41x/Singularity
@@ -50,9 +50,9 @@ echo 'GPU=amd ' >  gpu.txt  ; fi"
 export `cat ./gpu.txt`
 export `cat ./rocm_version.txt`
 export ROCM_PATH=/opt/rocm-${ROCM_VERSION}
-echo GPU is $GPU
+if [ ${#ROCM_VERSION} = 3 ]; then export ROCM_PATH="$ROCM_PATH".0; fi
 echo ROCM_PATH is $ROCM_PATH
-if [ "$ROCM_VERSION" = 6.0 ]; then export ROCM_PATH=/opt/rocm-${ROCM_VERSION}.0; fi
+echo GPU is $GPU
 export GCC_VERSION=11
 export TAMM_BRANCH=main
 
@@ -114,6 +114,8 @@ cd / \
 && echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/${ROCM_VERSION} jammy main' | tee --append /etc/apt/sources.list.d/rocm.list \
 && echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' |  tee /etc/apt/preferences.d/rocm-pin-600 \
 && apt-get  update -y &&  apt-get -y install hip-dev hip-runtime-amd rocm-llvm rocm-device-libs rocblas-dev openmp-extras \
+&& ls -lrt /opt \
+&& ls -lrt  /opt/rocm* || true \
 && wget --quiet https://download.amd.com/developer/eula/blis/blis-4-1/aocl-blis-linux-aocc-4.1.0.tar.gz -O - | tar xzf - -C /opt ; fi "  \
 && export kernelv=$(dpkg-query -W linux-headers-generic|cut -f2 ) \
 && echo kernelv is $kernelv \
@@ -126,7 +128,7 @@ cd / \
 && ls /lib/modules/$ktag  || true
  echo 'FC -v ' `$FC -v` 
  echo 'CC -v ' `$CC -v` 
- echo 'CXX -v ' `$CXX -v` 
+ echo 'CXX -v ' `$CXX -v` || { echo "CXX not installed"; exit  1; }
  apt-get clean 
  echo TTTTT 
  df -h 
@@ -204,15 +206,15 @@ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$ROCM_PATH"/lib
 if [ $(command -v mpicc) ]; then echo mpicc present; else echo mpicc missing; exit 1; fi 
  echo "which mpicc is" $(which mpicc)  \
 && echo "mpicc -show is " $(mpicc -show)  || { tail -700 $ompi_prefix/config.log ;echo "mpi compilation failed"; exit 1; } \
-&& echo ARMCI_NETWORK is $ARMCI_NETWORK 
- 	     echo TAMM_BRANCH is ${TAMM_BRANCH}  
- 	     echo 'cloning tamm source *** ' || true  
-              cd /opt || { echo "Failure"; exit 1; }  
-              git clone -b ${TAMM_BRANCH} --depth 100  https://github.com/ExaChem/exachem.git CoupledCluster   
-              git clone --depth 100 https://github.com/NWChemEx/TAMM.git  
- 	     cd TAMM  
-              git reset --hard 2033f021e0ff20c983a7ba2e9bd7e7cb2441bec6  
- 	     mkdir build && cd build  
+&& echo ARMCI_NETWORK is $ARMCI_NETWORK  \
+&& 	     echo TAMM_BRANCH is ${TAMM_BRANCH}   \
+&& 	     echo 'cloning tamm source *** ' || true   \
+&&            cd /opt || { echo "Failure"; exit 1; }  \
+&&              git clone -b ${TAMM_BRANCH} --depth 100  https://github.com/ExaChem/exachem.git CoupledCluster    \
+&&              git clone --depth 100 https://github.com/NWChemEx/TAMM.git   \
+&& 	     cd TAMM   \
+&&              git reset --hard 2033f021e0ff20c983a7ba2e9bd7e7cb2441bec6  \
+&& 	     mkdir build && cd build  
               CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/opt/install/CC -DMODULES=CC "  
  	     CMAKE_OPTIONS="$CMAKE_OPTIONS -DBLIS_CONFIG=zen3 -DMARCH_FLAGS=-march=znver3"  
  	     CMAKE_OPTIONS="$CMAKE_OPTIONS -DCMAKE_Fortran_FLAGS=-O0"  
