merge

diff --git a/apptainer.merge/Singularity b/apptainer.merge/Singularity
--- a/apptainer.merge/Singularity
+++ b/apptainer.merge/Singularity
@@ -7,6 +7,8 @@ MAINTAINER  Edoardo Apra <edoardo.apra@pnnl.gov>
    UBUNTU_VERSION=jammy
 
 %files
+autogen.sh /opt
+install-autotools.sh /opt
 #exachem_ecpint.patch /opt/
 
 %setup
@@ -295,7 +297,7 @@ then
     echo '$$$$$$$$$$$$$$$$$$$$' 
     wget --quiet https://download.amd.com/developer/eula/blis/blis-4-1/aocl-blis-linux-aocc-4.1.0.tar.gz -O - | tar xzf - -C /opt
 fi 
-echo 'FC -v ' `$FC -v` 
+echo 'FC --version ' `$FC --version` 
 echo 'CC -v ' `$CC -v` 
 echo 'CXX -v ' `$CXX -v` || { echo "CXX not installed"; exit  1; }
 apt-get clean 
@@ -305,7 +307,7 @@ if [ $UCX != "N" ]; then
     echo check ucx install 
     echo 'ls -l /opt/mpi/lib/libuct.so' $(ls -l /opt/mpi/lib/libuct.so) || true 
     if [ ! -f /opt/mpi/lib/libuct.so ]; then  
-	$FC -v 
+	$FC --version 
 	wget --progress=dot:giga  https://github.com/openucx/ucx/releases/download/$UCXVTAG/ucx-$UCX.tar.gz -O - | tar xzf - 
 	cd ucx-$UCX 
 	wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/ucx_malloc.patch 
@@ -442,7 +444,7 @@ if [ -n "${MPICH+1}" ]; then
     echo check mpich install 
     echo 'ls -l /opt/mpi/lib/libmpich.so' $(ls -l /opt/mpi/lib/libmpich.so) || true 
     if [ ! -f /opt/mpi/lib/libmpich.so ]; then
-	$FC -v
+	$FC --version
 #	if [ $MPICH = aurora ]; then
 #	fi 
 	if [ $mpich_major = '4' ] || [ $mpich_major = '5' ]; then
@@ -456,6 +458,16 @@ if [ -n "${MPICH+1}" ]; then
 	if [ $mpich_major = '3' ]; then
 	    wget https://raw.githubusercontent.com/pmodels/mpich/refs/tags/v4.3.2/src/pm/hydra/lib/tools/bootstrap/external/slurm_query_node_list.c 
 	    mv slurm_query_node_list.c src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
+	    echo 'mpich 3 autotools ' 
+	    mv autogen.sh autogen.sh.org 
+	    mv /opt/autogen.sh  .
+	    chmod +x autogen.sh 
+	    mv /opt/install-autotools.sh .
+	    chmod +x install-autotools.sh 
+	    wget https://github.com/pmodels/mpich/commit/3d351d49a07b401a35cb0e9b76fb077edca64eb9.patch 
+	    patch -p1 < 3d351d49a07b401a35cb0e9b76fb077edca64eb9.patch 
+	    cd maint/patches/optional/confdb && rm -f flang.patch &&  wget https://raw.githubusercontent.com/edoapra/exachem-container-images/main/apptainer.mpich/flang.patch ; cd ../../../../  ; pwd 
+	    sh ./autogen.sh 
 	fi
 	FC_short=$(basename -- $FC | cut -d \- -f 1 | sed 's/[0-9]*//g')
 	if [ ${FC_short} = "gfortran" ]
@@ -472,6 +484,8 @@ if [ -n "${MPICH+1}" ]; then
 	    --enable-fortran=all \
 	    --disable-opencl --enable-silent-rules \
 	    --disable-cuda \
+	    --without-ze  \
+	    --without-hip  \
 	    --with-xpmem=$MPI_DIR \
 	    FC=$FC || { echo "MPICH Configuration Failure"; exit 1; }
 	head config.log 
@@ -513,95 +527,146 @@ git clone -b ${TAMM_BRANCH} --depth 100 https://github.com/NWChemEx/TAMM.git
 cd TAMM  
 export NO_STOP_MESSAGE=1
 mkdir build && cd build 
-CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/opt/install/exachem -DMODULES='CC' " 
-CMAKE_OPTIONS="$CMAKE_OPTIONS -DBLAS_ARCH=zen3 -DMARCH_FLAGS=-march=znver3" 
-if [ ${GPU} = "nvidia" ]; then echo "nvidia gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_CUDA=ON -DGPU_ARCH=${GPU_ARCH}" ; fi 
-if [ ${GPU} = "amd" ]; then echo "amd gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_HIP=ON -DROCM_ROOT=$ROCM_PATH -DGPU_ARCH=${GPU_ARCH} -DGCCROOT=/usr " ; ls -lrt $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/ ; ln -sf $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/rocblas.h; fi  
-if [ ${ELPA} = "Y" ]; then echo "ELPA enabled "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_ELPA=ON" ; fi  
-CMAKE_OPTIONS="$CMAKE_OPTIONS -DGA_RUNTIME=${GA_RUNTIME}"
-export CMAKE_OPTIONS
-echo CMAKE_OPTIONS $CMAKE_OPTIONS 
-CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; } 
-make -j3 || { echo "TAMM Compilation failure"; 
-	    cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeOutput.log || true ; 
-            cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeError.log || true; exit 1; } 
-echo exit code for TAMM compilation $?  
-make install  
-echo exit code for TAMM make install $?  
-cd /opt/exachem  
-mkdir build && cd build  
-echo ' === ls -l /opt/install/exachem ===' $(ls -l /opt/install/exachem)  
-echo ' === ls -l /opt/install/exachem/lib ===' $(ls -l /opt/install/exachem/lib)  
-if [ -f /opt/install/exachem/lib/libint2.a ]
+CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX="\""/opt/install/exachem"\"" -DMODULES="\""CC"\"""  
+if [ ${GPU} != "intel_gpu_pvc" ]
 then
-    echo 'found libint cache'
+    CMAKE_OPTIONS="$CMAKE_OPTIONS -DBLAS_ARCH=zen3 -DMARCH_FLAGS=-march=znver3"
+fi
+CMAKE_OPTIONS="$CMAKE_OPTIONS -DGCCROOT=/usr" 
+if [ ${CC} = "icx" ]
+then
+    echo "intel compilers "
+    CMAKE_OPTIONS="$CMAKE_OPTIONS -DLINALG_VENDOR=IntelMKL  -DLINALG_PREFIX=${MKLROOT} "
+fi 
+if [ ${GPU} = "intel_gpu_pvc" ];
+then
+    echo "intel_gpu_pvc "; CMAKE_OPTIONS="$CMAKE_OPTIONS  -DUSE_OPENMP=OFF -DTAMM_ENABLE_DPCPP=ON "
+fi 
+if [ ${GPU} = "nvidia" ]; then
+    echo "nvidia gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_CUDA=ON -DGPU_ARCH=${GPU_ARCH}"
+fi  
+if [ ${GPU} = "amd" ]; then
+    echo "amd gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_HIP=ON -DROCM_ROOT=$ROCM_PATH -DGPU_ARCH=${GPU_ARCH} " ; ls -lrt $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/ ; ln -sf $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/rocblas.h
+fi  
+export USE_SCALAPACK=OFF 
+if [ ${SCALAPACK} = "y" ]
+then
+    echo "SCALAPACK ON"; CMAKE_OPTIONS="$CMAKE_OPTIONS -DUSE_SCALAPACK=ON "; export USE_SCALAPACK=ON
+fi  
+if [ \( ${CC} = "gcc" \) -a \(  ${ELPA} = "y" \) ]; then
+    echo "ELPA ON"; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_ELPA=ON "
+fi 
+if [ \( ${CC} = "amdclang" \) -a \( ${SCALAPACK} = "y" ) ]
+then
+    echo "scalapack workaround for clang "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DCMAKE_C_FLAGS_INIT='-Wno-error=implicit-function-declaration' 	"
+fi  
+CMAKE_OPTIONS="$CMAKE_OPTIONS -DGA_RUNTIME=${GA_RUNTIME}"  
+echo "modify ga repository to use" 
+CMAKE_OPTIONS="$CMAKE_OPTIONS -DGA_REPO="\""https://github.com/GlobalArrays/ga.git"\"" -DGA_TAG="\""develop"\"""    
+if [ ${GPU} = "intel_gpu_pvc" ]
+then
+    CMAKE_OPTIONS="$CMAKE_OPTIONS  -DTAMM_CXX_FLAGS="\""-mtune=sapphirerapids -ffast-math -ffp-contract=fast -fp-model=fast=2 -fsycl -fsycl-device-code-split=per_kernel -fsycl-targets=intel_gpu_pvc -mllvm -enable-global-offset=false"\"" -DUSE_LIBNUMA=OFF"
+fi 
+export CMAKE_OPTIONS   
+echo CMAKE_OPTIONS $CMAKE_OPTIONS  
+echo USE_SCALAPACK is set to $USE_SCALAPACK  
+rm -f doit.sh 
+echo   "USE_SCALAPACK=$USE_SCALAPACK CC=$CC CXX=$CXX FC=$FC \\" >>doit.sh  
+echo "cmake \\" >>doit.sh  
+echo "$CMAKE_OPTIONS  \\" >> doit.sh ; echo ".. " >>doit.sh  
+bash doit.sh || { echo "Cmake failure"; exit 1; }  
+make -j3 || { echo "Compilation failure in tamm step";
+              echo cublas $(ls -lrt $CUDA_PATH/lib64/libcublas*) || true ;  echo cublas target $(ls -lrt $CUDA_PATH/targets/x86_64-linux/lib64/libcublas*) ||true ;  echo ls cudapath $(ls -lrt $CUDA_PATH ) || true;  \
+	    cat $(find /opt/TAMM/ -name config.log) || true ; \
+	    cat $(find /opt/TAMM/ -name CMakeCache.txt) || true ; \
+	    cat $(find /opt/TAMM/ -name CMakeOutput.log) || true ; \
+            cat $(find /opt/TAMM/ -name CMakeError.log ) || true; exit 1; } 
+echo exit code for TAMM compilation $?   
+make install  
+echo exit code for TAMM make install $?   
+cd /opt/exachem 
+mkdir build && cd build   
+echo ' === ls -l /opt/install/exachem ===' $(ls -l /opt/install/exachem) 
+echo ' === ls -l /opt/install/exachem/lib ===' $(ls -l /opt/install/exachem/lib)   
+if [ -f /opt/install/exachem/include/libint2.h ]
+then
+    echo 'found libint cache' 
     mkdir -p /opt/exachem/build/stage/opt || true 
     rsync -av /opt/install /opt/exachem/build/stage/opt/.
-fi 
-export CMAKE_OPTIONS 
-echo CMAKE_OPTIONS $CMAKE_OPTIONS 
-CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; } 
-make V=1 VERBOSE=1 -j2 -l1.5 || { echo "Exachem Compilation failure"; exit 1; } 
-echo exit code for compilation $? 
-make install 
-echo exit code for make install $? 
+fi
+export CMAKE_POLICY_VERSION_MINIMUM=3.5 
+CMAKE_OPTIONS="$CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Release "
+if [ ${GPU} = "intel_gpu_pvc" ]; then
+    CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_CXX_FLAGS="\"" -mtune=sapphirerapids -ffast-math -fsycl -fsycl-device-code-split=per_kernel -fsycl-targets=intel_gpu_pvc -sycl-std=2020"\"""
+fi
+export CMAKE_OPTIONS
+echo CMAKE_OPTIONS $CMAKE_OPTIONS  
+rm -f doit.sh
+echo   " CC=$CC CXX=$CXX FC=$FC \\" >>doit.sh  
+echo "cmake \\" >>doit.sh  
+echo "$CMAKE_OPTIONS  \\" >> doit.sh ; echo ".. " >>doit.sh  
+bash doit.sh || { echo "Cmake failure"; exit 1; } 
+make V=1 VERBOSE=1 -j1 || { echo "Compilation failure"; exit 1; }  
+echo exit code for compilation $?  
+make install  
+echo exit code for make install $?  
 bash -c "if [[ -f /opt/install/exachem/bin/ExaChem ]]; then echo 'Exachem binary created' ; else  echo 'compilation error1'; exit 1; fi"  
-echo git describe --always `git describe --always`  >> /opt/install/info.txt
-echo git rev-parse HEAD git `git rev-parse HEAD` >> /opt/install/info.txt
-echo 'clean unnecessary source to reduce docker size'
-rm  -rf /opt/exachem
-rm  -rf /opt/*patch
-rm  -rf /opt/TAMM
-echo 'clean unnecessary packages '
-DEBIAN_FRONTEND=noninteractive apt-get -q=2 -y install localepurge
-echo MANDELETE >  /etc/locale.nopurge
-echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge
-echo en_US.UTF-8 >> /etc/locale.nopurge
-localepurge
-rm -rf /usr/share/doc
-apt-get -q=2 -y purge   patch curl  wget  make git cpp-"$GCC_VERSION" gfortran-"$GCC_VERSION" gcc-"$GCC_VERSION" libicu-dev libpython"$PY_VERSION"-dev libstdc++-"$GCC_VERSION"-dev libc6-dev libgcc-"$GCC_VERSION"-dev libgfortran-"$GCC_VERSION"-dev  || true
-apt-get -q=2 -y install libgfortran5 libgomp1 && apt-get clean
+echo git describe --always `git describe --always`  >> /opt/install/info.txt 
+echo git rev-parse HEAD git `git rev-parse HEAD` >> /opt/install/info.txt 
+echo 'clean unnecessary source to reduce docker size' 
+rm  -rf /opt/exachem 
+rm  -rf /opt/TAMM 
+echo 'clean unnecessary packages ' 
+DEBIAN_FRONTEND=noninteractive apt-get -q=2 -y install localepurge 
+echo MANDELETE >  /etc/locale.nopurge 
+echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge 
+echo en_US.UTF-8 >> /etc/locale.nopurge 
+localepurge 
+rm -rf /usr/share/doc 
+apt-get -q=2 -y purge   patch curl  wget  make git cpp-"$GCC_VERSION" gfortran-"$GCC_VERSION" gcc-"$GCC_VERSION" libicu-dev libpython"$PY_VERSION"-dev libstdc++-"$GCC_VERSION"-dev libc6-dev libgcc-"$GCC_VERSION"-dev libgfortran-"$GCC_VERSION"-dev  || true 
+apt-get -q=2 -y install libgfortran5 libgomp1 && apt-get clean 
 if [ "$GPU" = nvidia ]
 then
-    apt-get purge -y cuda-cccl-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcublas-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR"
-fi
+    rm -rf /usr/local/cuda*; apt-get purge -y cuda-cccl-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcublas-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcufft-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcufft-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcusolver-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcusparse-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libnpp-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcurand-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" cuda-nvrtc-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR"  libcufile-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" || true ; rm -f /usr/local/cuda-*/targets/x86_64-linux/lib/*static*a || true
+    fi
 if [ "$GPU" = "amd" ]
 then
-    apt-get  purge -y  cmake git-man openmp-extras \
-     lib32gcc-11-dev  libc6-dev-i386 libx32gcc-11-dev libc6-dev-x32 lib32gcc-11-dev  \
-     lib32asan6 lib32atomic1 lib32gcc-s1 lib32gomp1 lib32itm1 lib32quadmath0 lib32stdc++6 lib32ubsan1 libc6-i386 \
-     libc6-x32 libx32asan6 libx32atomic1 libx32gcc-s1 libx32gomp1 libx32itm1 libx32quadmath0 libx32stdc++6 libx32ubsan1 \
-     javascript-common less liberror-perl libjs-jquery libjs-sphinxdoc libjs-underscore libltdl-dev libltdl7 libpython3.10 linux-headers-generic
-    apt-get install -y hip-runtime-amd rocblas openmp-extras-runtime
+    apt-get  purge -y   git-man openmp-extras \
+    lib32gcc-11-dev  libc6-dev-i386 libx32gcc-11-dev libc6-dev-x32 lib32gcc-11-dev  \
+    lib32asan6 lib32atomic1 lib32gcc-s1 lib32gomp1 lib32itm1 lib32quadmath0 lib32stdc++6 lib32ubsan1 libc6-i386 \
+    libc6-x32 libx32asan6 libx32atomic1 libx32gcc-s1 libx32gomp1 libx32itm1 libx32quadmath0 libx32stdc++6 libx32ubsan1 \
+    javascript-common less liberror-perl libjs-jquery libjs-sphinxdoc libjs-underscore libltdl-dev libltdl7 libpython3.10  
+    apt-get install -y hip-runtime-amd rocblas openmp-extras-runtime rocm-smi-lib
     cd $ROCM_PATH/lib/rocblas/ ; mkdir keep ; mv library/*"$GPU_ARCH"* keep/.  
     rm -rf library ; mv keep library 
-    rm -rf "$ROCM_PATH"/bin  "$ROCM_PATH"/llvm/bin  
-    mkdir -p "$ROCM_PATH"/bin  && ln -sf "$ROCM_PATH"/libexec/rocm_smi/rocm_smi.py "$ROCM_PATH"/bin/rocm-smi
+    ln -sf "$ROCM_PATH"/ /opt/rocm 
+    rm  -f "$ROCM_PATH"/bin/rocm-smi ; ln -sf "$ROCM_PATH"/libexec/rocm_smi/rocm_smi.py "$ROCM_PATH"/bin/rocm-smi
+    rm -rf "$ROCM_PATH"/lib/hipblaslt || true 
+    rm -rf   "$ROCM_PATH"/llvm/bin
 fi
-echo '*** ls -l CC/bin **'
-ls -l /opt/install/exachem/bin/ || true
-echo '*** ldd ***' 
-LD_LIBRARY_PATH=/usr/local/lib:/opt/lib ldd /opt/install/exachem/bin/ExaChem || true
-DEBIAN_FRONTEND=noninteractive apt-get clean -y
-DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge
-echo MANDELETE >  /etc/locale.nopurge
-echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge
-echo en_US.UTF-8 >> /etc/locale.nopurge
-localepurge
-rm -rf /usr/share/doc  /usr/share/man
-du -sk /opt/*|sort -n
+echo '*** ls -l CC/bin **' 
+ls -l /opt/install/exachem/bin/ || true 
+echo '*** ldd ***'  
+ldd /opt/install/exachem/bin/ExaChem || true 
+DEBIAN_FRONTEND=noninteractive apt-get clean -y 
+DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge 
+echo MANDELETE >  /etc/locale.nopurge 
+echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge 
+echo en_US.UTF-8 >> /etc/locale.nopurge 
+localepurge 
+rm -rf /usr/share/doc  /usr/share/man 
+rm -rf /opt/exachem/build 
+rm -rf /opt/*patch  
+du -sk /opt/*|sort -n 
+echo "dddddddddddd"  
+dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 50 
 echo "dddddddddddd" 
-dpkg-query -Wf '${Installed-Sizet${Package}\n' | sort -n | tail -n 50 \
-echo "dddddddddddd"
- du -sk /tmp/* || true
- ls -lart /tmp ||true
-ls -Rlart  /opt/install/exachem || true
+du -sk /tmp/* || true 
+ls -lart /tmp ||true
+ls -Rlart  /opt/install/exachem || true 
 ls -lart  /opt/install/exachem/include || true
 ls -lart  /opt/install/exachem || true 
 
-#&&  apt-get  -y purge cmake git  gcc-11  g++-11  gfortran-11  libstdc++-11-dev  libgcc-11-dev git
-#&& apt-get -y install libgcc-s1 libgfortran5 \
-#&& apt-get -y autoremove && apt-get clean
 
 
 
